### ISSUE TITLE
OpenAI error in Backend

### ISSUE THREAD

**Issue by wolfgang007** [PIT-Solutions-Private-Limited/ai_translate#1]
Hi guys, 

if I try to use the OpenAI translation an error occurs: 

Client error: `POST https://api.openai.com/v1/chat/completions` resulted in a `404 Not Found` response: { "error": { "message": "The model `gpt-4` does not exist or you do not have access to it.", "type": (truncated...)

An API key is set. Any ideas?

Typo3 v12 & ai_translate 3.1.0

Best regards

![Unbenannt](https://github.com/PIT-Solutions-Private-Limited/ai_translate/assets/17067590/425df3e9-545f-4efd-8c57-a4a95a1f3d58)

**Comment by pitssavinmb** [comment]
Hi wolfgang007,

I think you are using open ai free account you need to add a payment plan and purchase credits to use the pay-per-use API: [Billing Overview](https://platform.openai.com/account/billing/overview). After making a successful payment (minimum $5) the gpt-4 model and higher rate limits should be enabled.

[https://community.openai.com/t/openai-error-invalidrequesterror-the-model-gpt-4-does-not-exist-or-you-do-not-have-access-to-it/376230](url)

**Comment by wolfgang007** [comment]
yes that was the problem. thx
