### ISSUE TITLE
Localize news records?

### ISSUE THREAD

**Issue by wolfgang007** [PIT-Solutions-Private-Limited/ai_translate#2]
Hi guys, 

the translation works great for content elements. 

But how it works for news records? Should there be a 2nd button? 

I added those lines: https://github.com/PIT-Solutions-Private-Limited/ai_translate?tab=readme-ov-file#translating-tca-records

If i click on the localize button, the default language is used.

Thx for feedback.

![Unbenannt](https://github.com/PIT-Solutions-Private-Limited/ai_translate/assets/17067590/6e3988f2-2eb3-4e6f-83e1-981b86970c5a)

**Comment by pitssavinmb** [comment]
This issue  fixed in ai_translate latest version 3.1.1

**Comment by pitssavinmb** [comment]
https://github.com/PIT-Solutions-Private-Limited/ai_translate?tab=readme-ov-file#translating-tca-records Follow this

**Comment by wolfgang007** [comment]
![typeerror](https://github.com/PIT-Solutions-Private-Limited/ai_translate/assets/17067590/63bfa094-987d-4414-ba6e-9d08177ce770)

**Comment by pitssavinmb** [comment]
Apply this patch file
[ai_translate-883e50e-Bug fix.patch](https://github.com/user-attachments/files/15782363/ai_translate-883e50e-Bug.fix.patch)

**Comment by pitssavinmb** [comment]
We are closing this issue now.
If this issue still exists please comment the issue
