### ISSUE TITLE
Translation of Content Elements in Container (s) not directly works - Container children are not recognized

### ISSUE THREAD

**Issue by enilee** [PIT-Solutions-Private-Limited/ai_translate#3]
Hi guys,

the translation works great for normal content elements.
But how it works for elements in containers?

My System:
TYPO3 12.4.11
container 2.3.1
ai_translate 3.1.0

I tested the following ways and found out the following:

1. Container with 2 columns, one text element in each column
After I clicked "Translate (deepl)", ONLY the container was displayed as an element to be translated, not the text elements.
The standard language was used, no translation into EN.

2. After I deleted a text element in English (same translated container) and clicked "Translate (deepl)" again, 
the text element to be translated was displayed and translated correctly.

To me it looks as if ai_translate does not recognize the elements within the container, does not display them and therefore does not translate them.
Only the 1. Level/depth of content, no nesting.

The technology exists and works, but it doesn't work the 1st time, but only when individual elements are deleted from the container that has already been translated and retranslated

i look forward to this optimization

---

<img width="1386" alt="image" src="https://github.com/PIT-Solutions-Private-Limited/ai_translate/assets/17785409/91bf2f6a-572b-49f4-a8df-8dbc5a67f559">

<img width="2127" alt="image" src="https://github.com/PIT-Solutions-Private-Limited/ai_translate/assets/17785409/0b0538a1-6aeb-4012-9990-8adfe1014111">

<img width="2113" alt="image" src="https://github.com/PIT-Solutions-Private-Limited/ai_translate/assets/17785409/c5828b9e-65d2-4917-b29f-b4b58341c89f">

<img width="2117" alt="image" src="https://github.com/PIT-Solutions-Private-Limited/ai_translate/assets/17785409/7e6c2adc-34ab-4ce8-b078-0b67b2426b0b">

<img width="2142" alt="image" src="https://github.com/PIT-Solutions-Private-Limited/ai_translate/assets/17785409/06079120-f6bf-4083-978e-58a05eec2dfb">

<img width="2128" alt="image" src="https://github.com/PIT-Solutions-Private-Limited/ai_translate/assets/17785409/e7bfb117-2fe2-4d12-8174-4f6163260199">

**Comment by pitssavinmb** [comment]
This issue fixed in ai_translate latest version 3.1.1

**Comment by enilee** [comment]
I just tested the translation online via ai_translate.
Worked well on one side, but not on another (page – column elements) the breaks ( <br />) were swallowed up in text.

<h5><strong>Contact</strong></h5>
<p>test<br />test<br />test<br />test<br /><a href="mailto:info@test.de">info@test.de</a></p>

All <br /> have been removed!

**Comment by pitssavinmb** [comment]
You can apply this patch file
[ai_translate-26c06dc-Bug fix.patch](https://github.com/user-attachments/files/15798708/ai_translate-26c06dc-Bug.fix.patch)

**Comment by pitssavinmb** [comment]
We are closing this issue now.
If this issue still exists please comment the issue
