### ISSUE TITLE
Installing fails

### ISSUE THREAD

**Issue by msollmann** [PIT-Solutions-Private-Limited/ai_translate#6]
After installing with composer the sources are present in the vendor directory and there is an entry in composer.json, but neither the module appears nor the extension is listed in the extensions module. Other extension can be installed without problem.

TYPO3 12.4.15/16
ai_translate 3.1.1

**Comment by msollmann** [comment]
Tried with another typo3 installation: same result.

**Comment by pitssavinmb** [comment]
This issue fixed.

composer req pits/ai_translate
composer exec typo3 extension:setup
